<a href="https://colab.research.google.com/github/Dreadwolf26/MLBeginnerNotesKindleBook/blob/main/Chapter_2%263_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

list1 = [1,2,3,4]
list2 = [[1,2,3,4]]
list3 = [[1,2,3,4],[10,20,30,40,], [100,200,300,400]]
arr1 = np.array(list1)
arr2 = np.array(list2)
arr3 = np.array(list3)
print(type(arr1), type(arr2), type(arr3))

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [ ]:
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(4,)
(1, 4)
(3, 4)


In [ ]:
#linspace(start, stop, num)
#We will use linespace to create a Numpy array
#this gives us 5 easy spaced numbers start from 0 - 10
arr4 = np.linspace(0,10,5)
print(arr4)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
#accessing data from a np array
#this words the same way as slicing regular lists
print(arr1[-1])

4


In [ ]:
#selecting arrays that are nested within the same array
#Use two sets of square brackes
#the below selects the index 1 list and the index 3 element in that list
print(arr3[1][3])

40


In [ ]:
#You can slice by start:step:step syntax
print(arr3[1:6:2])

[[10 20 30 40]]


Think of arrays as tables
With the nested arrays arranged as rows
For example in arr4
The first array would be row one
The second row 2
the third row 3
The slice beofre the commas selects the rows while the slice after selects the columns

In [ ]:
#you can also slice a 2D array
#this slices the first nested list and the second
print(arr3[0:2, 2:4])

[[ 3  4]
 [30 40]]


ndarray methods



*   You write the array name followed by a dot and the function you are wanting to call. Example: arr4.sum() This will sum the entire arr4. This only happens if you do not specify its axis. If specifying the axis you will sum the row, so if axis = 1 it will sum row one.



In [ ]:
#intializing new arr1 list to work through text book examples
arr1 = np.array([[1,2,3,4], [5,6,7,8]])

In [ ]:
#this output will add the first 2 digits of the send list in the array
print(arr1.sum(axis=1))

[10 26]


In [ ]:
#prints the sum of the entire array
print(arr1.sum())

36


reshape() method

reshape gives numpy arrays a new shape without changing any of the data within the array

recalling the 2D arrays. The tuples with 2 values.

Suppose we have a 1D array with 8 elements and we want to reshape it to a (4,2) 2D array

It is essential to now how to reshape 1D arrays to 2D because some of the modules in Scikit-Learn require 2D arrays as input

See code example below:



In [ ]:
arr2 = np.array([1,2,3,4,5,6,7,8])
#When calling reshape below to reshape the array you are creating 4 rows with
#2 columns
#you can observe the printed outputs below
reshaped_array = arr2.reshape((4,2))
print(arr2)
print(reshaped_array)

[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


You can always reshape arrays without defining specifics for columns or rows.

This can be accomplished by passing (n, -1) n being the specified number of rows. Or (-1, n) This will infer the shape for us. The -1 means unspecified.

Se example below:



In [ ]:
arr3 = np.array([1,2,3,4,5])
#reshaping the array
reshaped_array_2 = arr3.reshape((1,-1))
#printing the regualr array
print(arr3)
#printing the array in 2D with 1 row and 5 columns
print(reshaped_array_2)

[1 2 3 4 5]
[[1 2 3 4 5]]


Nmpy Functions

The previous section was about methods that are defined inside of an ndarray.

These functions will be used outside of the ndarray class.



1.   concatenate() this is used to combine two or more NumPy arrays. When joining two arrays you will want to join along axis 0 or axis 1. axis 0 requires that the arrays have the same numver of columns while axis 1 requires that the array has the same number of rows.
2.   List item



In [ ]:
arr1 = np.array([[1,2],[3,4], [5,6]])
arr2 = np.array([[7,8]])
#this will append arr2 to arr1
combined_array = np.concatenate((arr1, arr2))
print(combined_array)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
#We are now going to combine the array on axis 1 since the new array has 4 rows
arr3 = np.array([[9], [10], [11], [12]])
combined_array= np.concatenate((combined_array, arr3),axis=1)
print(combined_array)

[[ 1  2  9]
 [ 3  4 10]
 [ 5  6 11]
 [ 7  8 12]]


Wrapper Functions

Wrapper funstions are what wrap around corresponding methods or arrays.

This is why the double quotations happened in the .concatinate and reshape funstions.

# Chapter 3 Pandas

Pandas is an opensourse library that is built on top of NumPY.

It provides us with new data stuctures such as: Series and DataFrames and is designed to work well with tabular data.

A pandas series is a 1D (one dimensional) Data structure.

A DataFrame is a 2D (two dimensional) labeled data structure.

In [ ]:
import pandas as pd

list1 = [1,2,3,4,5]
print(list1, end='\n\n')
#this will print the series in a vertical line
series1 = pd.Series(list1)
print(series1, end='\n\n')
#this will print the series in a vertical line
series2 = pd.Series(list1, index=['P', 'Q', 'R', 'S', 'T'])
print(series2, end='\n\n')
#combining the above will list each series in a vertical line next to each other

#The column on the left will be the index of the series

[1, 2, 3, 4, 5]

0    1
1    2
2    3
3    4
4    5
dtype: int64

P    1
Q    2
R    3
S    4
T    5
dtype: int64



# Creating a pandas Dataframe

A DataFrame is similiar to a series except it is two dimensional.

To create a DataFrame we use the DataFrame() constructor.

Se example below:



In [ ]:
#creating a 2D list
'''When using 2D list the nested lists in the list
form the rows of the DataFrame'''

myList = [[1,2,3], [4,5,6]]
df1 = pd.DataFrame(myList)
print(df1, end='\n\n')

'''when using dictionary of lists the
lists of the dictionary form the columns'''

#Create from a dictionary of lists
myDict = {"A":[1,2,3], 'B':[4,5,6]}
df2= pd.DataFrame(myDict)
print(df2,end='\n\n')


   0  1  2
0  1  2  3
1  4  5  6

   A  B
0  1  4
1  2  5
2  3  6



In [ ]:
'''We can specify the labels of a DataFrame when creating it
To do that we use the index (for row labels)
and columns (for column labels)'''

myList2 = [[1,2,3,4,5], [10,20,30,40,50]]
df3 = pd.DataFrame(myList2, index = ['A', 'B'], columns = ['1st', '2nd', '3rd', '4th', '5th'])
print(df3)

   1st  2nd  3rd  4th  5th
A    1    2    3    4    5
B   10   20   30   40   50


# Using read_csv()

Generally we will use csv files to be able to us as a pandas function to reacd the data rather than creating it
manually.

When using CSV in google colab the file will have to be uploaded manually each time.

In [ ]:
#Reading PandasDemo files

classData = pd.read_csv('pandasDemo.csv')
print(classData)

   ModuleID Instructor      TA  Enrolment  Rating
0     CS101      Aaron    Vera       38.0     9.0
1     CS101       Beth   Carol        NaN     9.0
2     CS101     Calvin    Andy       28.0     7.0
3     CS102        Dan  Zidane       39.0     6.0
4     CS102      Aaron    Andy       32.0     NaN
5     CS102       Beth    Vera        NaN     7.0
6     CS103      Peter     Tim       40.0     8.0
7     CS103        Eve   Faith       39.0     9.0
8     CS103       Gail  Wesley       30.0     NaN
9     CS104      Aaron    Vera       30.0     8.0
10    CS104        Dan     Tim       30.0     NaN


# 3.6 Exploring data in a DataFrame

When lodig the data into a data frame we want to have a quick look at the data.

This can be accomplished by using the head() method. This method shows the first 5 rows of the DataFrame. If we want more than 5 rows we pass an integer in as an argument.

Se examples Below:



In [ ]:
import pandas as pd

classData = pd.read_csv('pandasDemo.csv')
#displays the first 4 rows by default
#classData.head()
#Then passing an intger in to display a specified number
classData.head(8)

ModuleID Instructor      TA  Enrolment  Rating
0    CS101      Aaron    Vera       38.0     9.0
1    CS101       Beth   Carol        NaN     9.0
2    CS101     Calvin    Andy       28.0     7.0
3    CS102        Dan  Zidane       39.0     6.0
4    CS102      Aaron    Andy       32.0     NaN
5    CS102       Beth    Vera        NaN     7.0
6    CS103      Peter     Tim       40.0     8.0
7    CS103        Eve   Faith       39.0     9.0

In [ ]:
#We can also generate descriptive statistics using the describe() method
classData.describe()

Enrolment    Rating
count   9.000000  8.000000
mean   34.000000  7.875000
std     4.873397  1.125992
min    28.000000  6.000000
25%    30.000000  7.000000
50%    32.000000  8.000000
75%    39.000000  9.000000
max    40.000000  9.000000

In [ ]:
'''3.7 Changing labels of row(s) and column(s)
We can use the rename() method and pass in the index and column parameters'''
'''When using the rename method and calling your index to rename.
It is label as a dictionary for column names. The key is the current row name.
The value is the name you are wanting to replace it with.
the index replaces the row names.
'''
classData = classData.rename(columns={'TA':'Assistant'}, index={0:'Row Zero', 1: 'Row One'})
classData.head()

ModuleID Instructor Assistant  Enrolment  Rating
Row Zero    CS101      Aaron      Vera       38.0     9.0
Row One     CS101       Beth     Carol        NaN     9.0
2           CS101     Calvin      Andy       28.0     7.0
3           CS102        Dan    Zidane       39.0     6.0
4           CS102      Aaron      Andy       32.0     NaN

# 3.8.1 Selecting data from a DataFrame

When can select one or more columns from our DataFrame and assign the results to a variable.

To select one column we use the columns label. This gives us a pandas Series:



In [ ]:
# this is selecting the ModuleID column and showing its type change
X1 = classData['ModuleID']
print(type(X1))
#Double Brackets cause it to be type DataFrame
X2 = classData[['ModuleID']]
#This selects just the ModuleID and Instructor columns
X3 = classData[['ModuleID', 'Instructor']]
print(type(X2))
print(type(X3))
X3.head()

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>


ModuleID Instructor
Row Zero    CS101      Aaron
Row One     CS101       Beth
2           CS101     Calvin
3           CS102        Dan
4           CS102      Aaron

# 3.8.2 Selecting Rows

# Using Boolean Arrays

To select rows we can use Boolean arryas. Suppose we want to select all the rows in classData where moduleID equals 'CS101

Se example Below:



In [ ]:
#This will give us true/false values if that data is present or not.
arr1 = classData['ModuleID'] == 'CS101'
print(arr1)

Row Zero     True
Row One      True
2            True
3           False
4           False
5           False
6           False
7           False
8           False
9           False
10          False
Name: ModuleID, dtype: bool


In [ ]:
#we can now use this series to select the rows we want
#Since we have defined the boolean values above we do not need to define them again
classData[arr1]

ModuleID Instructor Assistant  Enrolment  Rating
Row Zero    CS101      Aaron      Vera       38.0     9.0
Row One     CS101       Beth     Carol        NaN     9.0
2           CS101     Calvin      Andy       28.0     7.0

In [ ]:
'''If we want to use more than one cition we can use the
& sing for the (and conditional) and | for the (or conditional)'''
arr1 = classData['ModuleID'] == 'CS101'
arr2 = ['Instructor'] == 'Aaron'
classData[arr1 & arr2]

Empty DataFrame
Columns: [ModuleID, Instructor, Assistant, Enrolment, Rating]
Index: []

In [ ]:
#A quicker way to write the above
#This is used if we do not want to assign variables to sort the info
#unsure why this method worked and the above did not
classData[(classData['ModuleID'] == 'CS101') & (classData['Instructor'] == 'Aaron')]

ModuleID Instructor Assistant  Enrolment  Rating
Row Zero    CS101      Aaron      Vera       38.0     9.0

# Using iloc[] or loc[]

We can using these to select rows rather than using boolean arrays

iloc[] is primary for selecting by position. For exmaple: by row numbers starting from 0.

loc[] is for by selecting the row by its label

See code examples below:



In [ ]:
#This selects row at index 0
classData.iloc[0]

ModuleID      CS101
Instructor    Aaron
Assistant      Vera
Enrolment      38.0
Rating          9.0
Name: Row Zero, dtype: object

In [ ]:
#This also selects information at Row Zero but by label name
classData.loc['Row Zero']

ModuleID      CS101
Instructor    Aaron
Assistant      Vera
Enrolment      38.0
Rating          9.0
Name: Row Zero, dtype: object

In [ ]:
#selecting row as a DataFrame or select more than one row we use a list

classData.iloc[[0, 3, 4]]  # For selecting rows based on integer positions
classData.loc[['Row Zero', *classData.index[[3, 4]]]]  # For selecting rows based on a mix of labels and integer positions


ModuleID Instructor Assistant  Enrolment  Rating
Row Zero    CS101      Aaron      Vera       38.0     9.0
3           CS102        Dan    Zidane       39.0     6.0
4           CS102      Aaron      Andy       32.0     NaN

In [ ]:
#You can also slice to select rows
#this produces the first 3 rows in the data set
classData.iloc[0:3]

ModuleID Instructor Assistant  Enrolment  Rating
Row Zero    CS101      Aaron      Vera       38.0     9.0
Row One     CS101       Beth     Carol        NaN     9.0
2           CS101     Calvin      Andy       28.0     7.0

# 3.8.3 Selecting Rows and columns

We do this by first specifying the row(s) followed by a comma and then the column(s) we want.

See exmaples below:



In [ ]:
#Selecting rows 0 to 4 and columsn 0 to 1
classData.iloc[0:4, 0:2]

ModuleID Instructor
Row Zero    CS101      Aaron
Row One     CS101       Beth
2           CS101     Calvin
3           CS102        Dan

In [ ]:
#will select all the rows based on a specific column
classData.iloc[:, 2]

Row Zero      Vera
Row One      Carol
2             Andy
3           Zidane
4             Andy
5             Vera
6              Tim
7            Faith
8           Wesley
9             Vera
10             Tim
Name: Assistant, dtype: object

In [ ]:
#slecting all of the colums except the last column.
#columns are denoted after the comma : selects all -1 excludes the last column
classData.iloc[:, :-1]

ModuleID Instructor Assistant  Enrolment
Row Zero    CS101      Aaron      Vera       38.0
Row One     CS101       Beth     Carol        NaN
2           CS101     Calvin      Andy       28.0
3           CS102        Dan    Zidane       39.0
4           CS102      Aaron      Andy       32.0
5           CS102       Beth      Vera        NaN
6           CS103      Peter       Tim       40.0
7           CS103        Eve     Faith       39.0
8           CS103       Gail    Wesley       30.0
9           CS104      Aaron      Vera       30.0
10          CS104        Dan       Tim       30.0

# 3.9 Updating a DataFrame

We can update a DataFrame by adding a column to it or by updating exsisting columns

See examples below:



In [ ]:
classData['AverageGPA'] = [44,46,47,41,45,49,40,41,45,48,42]
#adding GPA to table
#this multiples all of the values in by 0.1 to create a float
classData['AverageGPA'] = classData['AverageGPA']*0.1
#Display first 4 rows of data
classData.head()

ModuleID Instructor Assistant  Enrolment  Rating  AverageGPA
Row Zero    CS101      Aaron      Vera       38.0     9.0         4.4
Row One     CS101       Beth     Carol        NaN     9.0         4.6
2           CS101     Calvin      Andy       28.0     7.0         4.7
3           CS102        Dan    Zidane       39.0     6.0         4.1
4           CS102      Aaron      Andy       32.0     NaN         4.5

# 3.10 Useful Methods in Pandas

# sort_values()

This methods sorts a DataFrame in ascending order by default. If you are wanting the order to be descinding you will have to pass in ascending = False as an argument.

#isnull()

returns a DataFrame where missing values in the original DataFrame gets mapped to True while other values get mapped to false.

In [ ]:
#Thsi will sort by rating and AverageGPA in descinding order
#note how the arguments are passed in
classData.sort_values(['Rating', 'AverageGPA'], ascending=False)

ModuleID Instructor Assistant  Enrolment  Rating  AverageGPA
Row One     CS101       Beth     Carol        NaN     9.0         4.6
Row Zero    CS101      Aaron      Vera       38.0     9.0         4.4
7           CS103        Eve     Faith       39.0     9.0         4.1
9           CS104      Aaron      Vera       30.0     8.0         4.8
6           CS103      Peter       Tim       40.0     8.0         4.0
5           CS102       Beth      Vera        NaN     7.0         4.9
2           CS101     Calvin      Andy       28.0     7.0         4.7
3           CS102        Dan    Zidane       39.0     6.0         4.1
4           CS102      Aaron      Andy       32.0     NaN         4.5
8           CS103       Gail    Wesley       30.0     NaN         4.5
10          CS104        Dan       Tim       30.0     NaN         4.2

# isnull() method

Returns a DataFrame where missing values in the original DataFrame gets mapped to True while other values get mapped to false.

In [ ]:
import numpy as np
#note how index 0 and 1 is None and NaN respectively these would mean missing data
myData = pd.DataFrame([[None], [np.NaN], [''], ['Apple']], columns = ['A'])
print(myData.isnull())
#this will sum all the areas that has missing values
myData.isnull().sum()

       A
0   True
1   True
2  False
3  False


A    2
dtype: int64

In [ ]:
#to check null data in classData
classData.isnull().sum()

ModuleID      0
Instructor    0
Assistant     0
Enrolment     2
Rating        3
AverageGPA    0
dtype: int64

# dropna() method

machine learning algorithms will not work with missing values. To handle these values we can delete them by using the dropna() method.

By default this will delete entire rows of data that is missing a value if we want to delete columns instead we need to pass in axis = 1



In [ ]:
#this method drops the row with missing data
classData_rows_deleted = classData.dropna()
#this drops the column of missing data
classData_columns_deleted = classData.dropna(axis = 1)
print(classData_columns_deleted)
print(classData_rows_deleted)
####IMPORTANT NOTE THIS DOES NOT ALTER THE ORGINAL DATA IT MAKES A COPY

         ModuleID Instructor Assistant  AverageGPA
Row Zero    CS101      Aaron      Vera         4.4
Row One     CS101       Beth     Carol         4.6
2           CS101     Calvin      Andy         4.7
3           CS102        Dan    Zidane         4.1
4           CS102      Aaron      Andy         4.5
5           CS102       Beth      Vera         4.9
6           CS103      Peter       Tim         4.0
7           CS103        Eve     Faith         4.1
8           CS103       Gail    Wesley         4.5
9           CS104      Aaron      Vera         4.8
10          CS104        Dan       Tim         4.2
         ModuleID Instructor Assistant  Enrolment  Rating  AverageGPA
Row Zero    CS101      Aaron      Vera       38.0     9.0         4.4
2           CS101     Calvin      Andy       28.0     7.0         4.7
3           CS102        Dan    Zidane       39.0     6.0         4.1
6           CS103      Peter       Tim       40.0     8.0         4.0
7           CS103        Eve     Faith

# to_numpy() method

Converts a Pandas series or a DataFrame to a NumPy array

The code below demonstrates the more from a Pandas Dataframe to a numpy array and printing its type along the way.

In [ ]:
myData2 = pd.DataFrame([[1,2], [3,4]], columns= ['A', 'B'])
myArr = myData2.to_numpy()
print(type(myData2))
print(myData2)
print(type(myArr))
print(myArr)

<class 'pandas.core.frame.DataFrame'>
   A  B
0  1  2
1  3  4
<class 'numpy.ndarray'>
[[1 2]
 [3 4]]


# corr() method

This method gives us the pairwise correlation coefficients.

I needed an explanation of pairewise correlation coefficients and GPT delivered:

Pairwise correlation coefficients are a way to measure how two variables change together. In the context of machine learning, it helps us understand how two different features (or variables) in our dataset are related to each other.

Imagine you have a dataset with two features: "Hours of study" and "Exam score." Pairwise correlation coefficient tells you whether there's a relationship between these two features, and if so, how strong it is.

Here's a simple breakdown:

1. **What it measures**: Pairwise correlation coefficient measures the strength and direction of the relationship between two variables.

2. **Values it can take**: The value of a correlation coefficient ranges between -1 and 1.
   - A correlation of 1 means a perfect positive relationship: as one variable increases, the other also increases.
   - A correlation of -1 means a perfect negative relationship: as one variable increases, the other decreases.
   - A correlation of 0 means there's no linear relationship between the variables.

3. **How it's calculated**: It's calculated using a formula that essentially measures how much the variables deviate from their respective means together.

4. **Interpreting the coefficient**:
   - A positive coefficient means the variables tend to move in the same direction: when one increases, the other tends to increase.
   - A negative coefficient means the variables tend to move in opposite directions: when one increases, the other tends to decrease.
   - The closer the coefficient is to 1 or -1, the stronger the relationship. A coefficient close to 0 indicates a weak or no relationship.

5. **Significance**: It's important to note that correlation doesn't necessarily imply causation. Just because two variables are correlated doesn't mean that changes in one cause changes in the other.

In summary, pairwise correlation coefficients help us understand how features in our dataset are related to each other, which can be useful in various machine learning tasks like feature selection, understanding dependencies, and preprocessing data.

See code examples below:

See docstring within code this will answer why you need to drop a column if the correlation is too high:

If the correlation between two columns (features) in your dataset is too high, it means that these two columns are providing very similar information. Having highly correlated features in your dataset can lead to several issues in machine learning models:

1. **Redundancy**: Highly correlated features essentially carry the same information. Having redundant features doesn't provide additional useful information to the model but can increase the complexity and computational cost.

2. **Overfitting**: When you have highly correlated features, your model might overweight the importance of these features, leading to overfitting. Overfitting occurs when a model learns the training data too well, including noise or irrelevant patterns, which results in poor generalization to unseen data.

3. **Interpretability**: In some cases, highly correlated features can make it difficult to interpret the model. It becomes unclear which feature is truly influencing the outcome, as both features provide similar information.

4. **Model Performance**: Highly correlated features can lead to instability in model performance. Small changes in the data or noise can cause large variations in the model's predictions.

By dropping one of the highly correlated columns, you can mitigate these issues. It helps to simplify the model, reduce overfitting, and improve interpretability. However, it's essential to choose which column to drop carefully, considering domain knowledge, the importance of the features, and the specific requirements of the machine learning task. Typically, you might keep the feature that is more interpretable or has more significance in the context of the problem you're solving.

In [ ]:
myData3 = pd.DataFrame({'A': [1,4,7,10], 'B':[1,2,3,4], 'C': [2,12,1,5]})
#print the sample DataFrame for reference
print(myData3)
#calling corr()
myData3.corr()
'''So we can see here with the correlation below
The table below is symmetrical about the diaganol
so we can then focus on the coefficients within
the trianlge. This shows A and B are perfectly correlated
Therefore we can drop Column A or B from the dataset. See text above'''

    A  B   C
0   1  1   2
1   4  2  12
2   7  3   1
3  10  4   5


'So we can see here with the correlation below\nThe table below is symmetrical about the diaganol\nso we can then focus on the coefficients within\nthe trianlge. This shows A and B are perfectly correlated\nTherefore we can drop Column A or B from the dataset. See text above'